spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    static-path-pattern: /resources/**/**
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoshop
    username: postgres
    password: postgres
    liquibase:
      enabled: true
  sql:
    init:
      platform: postgresql
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
  messages:
    basename: validation
  logging:
    config: class-path:logback.xml
  level:
    com.demoshop.demoshop: info
  file:
    name: logs/demoShop-service.log

