spring:
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    static-path-pattern: /resources/**/**
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoshop
    username: postgres
    password: Ihubev1488228_
    liquibase:
      enabled: true
  sql:
    init:
      platform: postgresql
