spring:
  mvc:
    static-path-pattern: /resources/**/**
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoshop
    username: postgres
    password: postgres
    liquibase:
      enabled: true
  sql:
    init:
      platform: postgresql
