spring:
  mvc:
    static-path-pattern: /resources/**/**
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Store
    username: postgres
    password: 123
    liquibase:
      enabled: true
  sql:
    init:
      platform: postgresql
  logging:
    config: class-path:logback.xml
  level:
    com.demoshop.demoshop: info
  file:
    name: logs/demoShop-service.log

